apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-java
  labels:
    app: springboot-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-java
  template:
    metadata:
      labels:
        app: springboot-java
    spec:
      containers:
        - name: springboot-java
          image: harshitha0117/springboot-java:9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
