apiVersion: v1
kind: Service
metadata:
  name: springboot-java
  labels:
    app: springboot-java
spec:
  type: NodePort
  selector:
    app: springboot-java
  ports:
    - port: 8080
      targetPort: 8080